// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: Hello.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClientStream_ServerReply_FullMethodName = "/ClientStream/ServerReply"
)

// ClientStreamClient is the client API for ClientStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientStreamClient interface {
	ServerReply(ctx context.Context, opts ...grpc.CallOption) (ClientStream_ServerReplyClient, error)
}

type clientStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStreamClient(cc grpc.ClientConnInterface) ClientStreamClient {
	return &clientStreamClient{cc}
}

func (c *clientStreamClient) ServerReply(ctx context.Context, opts ...grpc.CallOption) (ClientStream_ServerReplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientStream_ServiceDesc.Streams[0], ClientStream_ServerReply_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clientStreamServerReplyClient{stream}
	return x, nil
}

type ClientStream_ServerReplyClient interface {
	Send(*CReqt) error
	CloseAndRecv() (*SReply, error)
	grpc.ClientStream
}

type clientStreamServerReplyClient struct {
	grpc.ClientStream
}

func (x *clientStreamServerReplyClient) Send(m *CReqt) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientStreamServerReplyClient) CloseAndRecv() (*SReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStreamServer is the server API for ClientStream service.
// All implementations must embed UnimplementedClientStreamServer
// for forward compatibility
type ClientStreamServer interface {
	ServerReply(ClientStream_ServerReplyServer) error
	mustEmbedUnimplementedClientStreamServer()
}

// UnimplementedClientStreamServer must be embedded to have forward compatible implementations.
type UnimplementedClientStreamServer struct {
}

func (UnimplementedClientStreamServer) ServerReply(ClientStream_ServerReplyServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerReply not implemented")
}
func (UnimplementedClientStreamServer) mustEmbedUnimplementedClientStreamServer() {}

// UnsafeClientStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStreamServer will
// result in compilation errors.
type UnsafeClientStreamServer interface {
	mustEmbedUnimplementedClientStreamServer()
}

func RegisterClientStreamServer(s grpc.ServiceRegistrar, srv ClientStreamServer) {
	s.RegisterService(&ClientStream_ServiceDesc, srv)
}

func _ClientStream_ServerReply_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStreamServer).ServerReply(&clientStreamServerReplyServer{stream})
}

type ClientStream_ServerReplyServer interface {
	SendAndClose(*SReply) error
	Recv() (*CReqt, error)
	grpc.ServerStream
}

type clientStreamServerReplyServer struct {
	grpc.ServerStream
}

func (x *clientStreamServerReplyServer) SendAndClose(m *SReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientStreamServerReplyServer) Recv() (*CReqt, error) {
	m := new(CReqt)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStream_ServiceDesc is the grpc.ServiceDesc for ClientStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClientStream",
	HandlerType: (*ClientStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerReply",
			Handler:       _ClientStream_ServerReply_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Hello.proto",
}
